// let dna = "TATCGTCCGTCTACAACTCAACTGATATTGACGTTGAGTTGCCGCTGCTGGCTTTTATACTGGGTGAAAGCATGGAAGGATATGATTTAACCCACTAAACACCGACTAAACATCGGTGCCAGCTAATCCGCTAAGTAAGTATAGATCCAACGTCTGCGTACGGCGAATGCTCAAGCGTACAATGGGGGTGATACGGTGGGATAGGTGGAAGTCCCTTGCACCAATAGTGTAAAGTAAAACTCGATGGGAGGATACCGTAGGCCTGTGTCAAAACGATCAGTACCAGCCGTAGTAAACTCCCTAGTAGTGGGTCGGGGTTCTTGAATGAGAAGCTTACGGGTAGCGTTTGAGCTTCCCTCCTCTACCTAAACGTATTACTTCATGTACTGCATATCTTTCCACTCGGACCCCTCTTGATCACTAACCAAAAGGGCACTACACCGTCCGCTACTACTTTCGACAGCTGTAGAAGTTACCAGCTACTCAGGAACTGATGGGGAACTAGCCCGCGGGAGAACAAGACCTGTGAGAACCGTTAGACAGTTAGATGAGTGGGCACGCTGGTAGATCCTCCAGGCATAATATAGTATTCTAAACGAGCTCGGCACGGGGTATAATACCAGAATTGTGCATAACCGACCTGGACGACATCAACGTACGGTCTACCCACTCTAAGTTGCGAAACCATCGTATTGTGAGCCATCGCTCAGACCCACATAAGAAAAGCAGGGTCCTAGTTTGTCTGTATAGATGGTGATGGAACCGTGCAATTGTCCGTAGAGGTGCCAGTGAACACGCGGTATTGAGGCAAG"

// let cnts = [];
// cnts[0] = 0;
// cnts[1] = 0;
// cnts[2] = 0;
// cnts[3] = 0;
// for (var i = 0; i < dna.length; i++) {
//     switch (dna[i]) {
//         case "A": cnts[0]++; break;
//         case "C": cnts[1]++; break;
//         case "G": cnts[2]++; break;
//         case "T": cnts[3]++; break;
//     }
// }
// console.log(cnts[0] + " " + cnts[1] + " " + cnts[2] + " " + cnts[3]);

// let dna = "GAGCTAGGCTCCAAACGACAGGATGACCTTTACGAGCGATAATGGGATGGATACTTCTCACTTCCAACTCCAACTCCGACGGAACGATCACGCTTCGGACGACTCGTGGGAGATTCGGCTCCACTGTTAACGGACGCGCTTGGGCTGAAAAAGCGTATTAGGTACCCGAGACGGGCGGTGTCTTCAGCCTCGACCTGTAACCTGACGTCTCGCCTCGCAGAGCGCTAACGAGCCACGGATTCTGCGAGCTCTCGTATTGGGTAGCTTCCCTCTCATATTCTTACGCCGTAAGCCACACCCCCACCGAGATTCGCAGGACGGGGTAAATTGAACATCCCGACGTGTGCCAAACTCAGGGAGTTCCTCAATAGATGCTTATAATTAACTACAGTGAATCTTTACAAAGAGTGAACAGAGGGCTTATTAGCCACTACACATCGTTGCACAACAGAGATTACTGGGAATGAGACATAGCCTGCGCATAAGTAGAGGACTTTGGTGAACGGCGCTGTTCATATTCTTACTAGAACTGTAAGAAGGTCTTAGACCTCACTTGGTCGATTCATAGGTTTCCCTTACCTGCAGCCACTAAATCGGAGCACGGACGTTATTAGAAGTCAAAGCTTATGGTGCGGGAACACCATCCTGTAGGTTCACGGGTGTGGGATAGGTGGGCCACTGCTTTGCCGGGAAACCTATGGCGCGGGTCACTTTGGACACCATGGTATAGTGCGGTTGTTTCATGATCTCCACACACAACTTAGAAATATTGGCCTGGGGTAGGCATTATCCTTCGGTACTTGAGTATCGAAGGCGTACGAACACATGGAAAACACCAGGCATTCCGTCGGAGAGATTCGCACGAACTATGGGGTAAACTAGCCCTACCTACTGGTTATCCATAAAATTTTTAGCAACGTCGCTATCCGTTAACAATCGACTCGCTAACCAACAGTTGC";
// console.log(dna.replace(/T/gi, "U"));

// let dna = "TATGTGACTTAGGTATGAAAACTGAGCGGTTTCGTAGCGCCGGCCCAAGAACAAGCATTTGATAACGGAGCCACGTGATGATCCGCGGTAATGCCCGGTCACATCGGCGGCCTCTCGGCCGTACATACAAGCACCTGGATGGTTTGGGCACGTCCAAGCAGGTAGAATACTGCGCATCCCCCTGTTTGCAGGTGCAGGCCCTATCTGGCTGATAGCCTATTCTTAAGCTGGAGCTCATAAAACATGGCGGACGTTCTACTTTTATACCCTCCACCCTCTAACTGGGGTTCGCAATCTCCGGATACTCACGATTGATGGAACAGGATCGCCGTTTGATCTAGGGGTTTATACGGGGGAAATCGGACCCGGGAGAGTCACAAGACTGTGGGTTTTACGGACTCGTAATCTGATAACTAGCGTGTATCCTTTGATCGTCCTGCCTGATCTAGGGCGTGCACCACACCCATATCATACAATTATTCCGGCTCCTAGCTGTTGGCGGTTTTTGGTCAACTCAAGCTCCTTACTGCGTTTCCAGCAGCGAGAACCGACAATAACCCTGCCAAATCGACAAAGTTCCCTACTATACACCATTCCGGCGTCAGACACTTACAGCTCGCGGATGGCTTCTAACTCATCACAAGCATCAACAACCACCGTCACTGAAGCTTGGAGCGGTACATCCTCTAAGAACAGGTACAAACTATACCGCATTTATGTACTTGTAGAAACCGATACATATCCTCTCTGGTTATGGTCGTCACGTTCCCTGAGCAAGTTGTTGGCTCAGGCTGCGATGTAACCTTGAGATGGAGCATCGAGCTGTGGGA"
// let output = "";
// for (var i = dna.length - 1; i >= 0; i--) {
//     output += compliment(dna[i]);
// }
// function compliment(symbol) {
//     switch (symbol) {
//         case 'A': return 'T';
//         case 'C': return 'G';
//         case 'G': return 'C';
//         case 'T': return 'A';
//     }
// }
// console.log(output);


let dataset = "5 3";
let parts = dataset.split(" ");
let n = parseFloat(parts[0]);
let k = parseFloat(parts[1]);

let total = 2;
let table = [0, total];

for (let i = 2; i <= n; i++) {
    let mature = table[i - 1] + table[i - 2];
    let pairs = Math.floor(mature / 2.0);
    let kids = pairs * k * 2;
    table.push(kids);
    total += kids;
}

console.log(table);
console.log(total / 2);